name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: go file
      run: cd CampusMarket-backend
    - name: Build the Docker image
      run: docker build ./CampusMarket-backend --tag spring:$(date +%s) .
